# Generated by Django 5.2.4 on 2025-08-06 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobcategory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobcategory',
            old_name='name',
            new_name='category_name',
        ),
    ]
